apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-ac
  namespace: {{ .Release.Namespace }}
  labels:
    app: mock-ac
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mock-ac
  template:
    metadata:
      labels:
        app: mock-ac
    spec:
      containers:
      - name: mock-ac
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: PORT
          value: "{{ .Values.service.targetPort }}"
        - name: RESOURCE_ID
          value: "{{ .Values.config.resourceID }}"
        - name: BASE_URL
          value: "{{ .Values.config.baseURL }}"
        {{- if .Values.users }}
        - name: MOCK_AC_USERS
          value: {{ .Values.users | toJson | quote }}
        {{- end }}
        {{- if .Values.groups }}
        - name: MOCK_AC_GROUPS
          value: {{ .Values.groups | toJson | quote }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ac/availability
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
