apiVersion: v1
kind: Service
metadata:
  name: mock-ac
  namespace: {{ .Release.Namespace }}
  labels:
    app: mock-ac
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: mock-ac
