issuer: https://haproxy.cadc.dao.nrc.ca/dex

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556

staticClients:
  - id: science-portal
    redirectURIs:
      - https://haproxy.cadc.dao.nrc.ca/science-portal/oidc-callback
    name: Science Portal
    secret: CHANGE_ME_science_portal_secret
  - id: storage-ui
    redirectURIs:
      - https://haproxy.cadc.dao.nrc.ca/storage/oidc-callback
    name: Storage UI
    secret: CHANGE_ME_storage_ui_secret

enablePasswordDB: true

# Default admin user — password: Test123!
# Generate new hash: htpasswd -nbBC 10 "" 'YourPassword' | cut -d: -f2
staticPasswords:
  - email: admin@haproxy.cadc.dao.nrc.ca
    hash: $2y$10$VT7Zyul3YGQHggKdT6FKg.vph2IWyUgreuoa6rjd0LimPyvcZABtu
    username: admin
    preferredUsername: admin
    userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
