# Skaha — example values
# Hostnames and secrets are auto-configured by: npm run setup
# Bootstrap auto-syncs: gmsID, CA cert

deployment:
  hostname: haproxy.cadc.dao.nrc.ca
  skaha:
    registryURL: https://haproxy.cadc.dao.nrc.ca/reg
    oidcURI: https://haproxy.cadc.dao.nrc.ca/dex
    gmsID: ivo://cadc.nrc.ca/gms
    posixMapperResourceID: ivo://cadc.nrc.ca/posix-mapper
    skahaTld: haproxy.cadc.dao.nrc.ca
    usersGroup: ivo://cadc.nrc.ca/gms?skaha-users
    adminsGroup: ivo://cadc.nrc.ca/gms?skaha-admins
    headlessGroup: ivo://cadc.nrc.ca/gms?skaha-headless
    registryHosts: images.canfar.net images.opencadc.org
    oidc:
      uri: https://haproxy.cadc.dao.nrc.ca/dex
      clientID: science-portal
      clientSecret: CHANGE_ME
      callbackURI: https://haproxy.cadc.dao.nrc.ca/skaha/oidc-callback
      redirectURI: https://haproxy.cadc.dao.nrc.ca/skaha
      scope: openid profile offline_access
    sessions:
      maxCount: 5
      gpuEnabled: false
      userStorage:
        topLevelDirectory: /cavern
        homeDirectory: home
        projectsDirectory: projects
        persistentVolumeClaimName: skaha-workload-cavern-pvc
        serviceURI: ivo://cadc.nrc.ca/cavern
        nodeURIPrefix: vos://cadc.nrc.ca~cavern
  extraHosts:
    - ip: "10.0.0.1"
      hostname: haproxy.cadc.dao.nrc.ca

storage:
  service:
    spec:
      persistentVolumeClaim:
        claimName: skaha-pvc
