apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: {{ .Release.Namespace }}
  labels:
    app: dex
spec:
  type: ClusterIP
  ports:
    - port: 5556
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: dex
