apiVersion: v1
kind: Service
metadata:
  labels:
    run: doi-tomcat
  name: doi-tomcat
  namespace: {{ .Values.skaha.namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: doi-tomcat
  type: ClusterIP
